### PR TITLE
Website update

### PR DESCRIPTION
**Pull request by 7h3730B**
First I would like to apologize for the bad commit history but, 'cause of githubs git lfs restrictions on public forks I got some problems.
 
Anyway the site, inspired by [Klise](https://github.com/piharpi/jekyll-klise), has most of its groundwork done and is mostly functional but there are still things that need to be done and I got some questions.

## Questions:
1. I couldn't add the favicons, 'cause of the restrictions mentioned before. So could you add them yourself?
2. The original theme has a extra navbar for mobile devices but we only have to items. So is a mobile navbar really needed?
3. It would be nice to have a so called anchor on headings so you can share a link to a specific part of a blog post. For that feature to work however we need to parse markdown headings to a html heading with an `<a>` tag and a class on it. I'm not so confident in my Rust and especially in the rendering libary. Could you look into it?
4. Currently images are just gotten from the `/assets/img/image.png` directory but I assume you would like them to be grouped per post like `/assets/img/<post-name>/image.png`. I'm not trusting myself enough to implement that, 'cause I'm not really sure of the security risks, maybe I'm just overreacting and rocket is handling it the right way. But I would like to keep that task to you, if thats okay.

## TODO:
- [x] fix the theme switch icon so it's centered and visible even if dark mode is active
- [x] add code highlighting
- [x] add anchor headings
- [x] mobile navbar?
- [ ] favicon
- [x] add more meta:og tags for social platforms

I would like to hear your feedback! And if you still got any feature requests or ideas for improvement, let me know!

### CODE REVIEW

**Comment by vbe0201** [comment]
Thank you so much for helping out! I'm really happy with the current progress on this.

As for your questions:

1. No problem.
2. I intend to add more items myself so if it's not too much of a hassle, it would be greatly appreciated.
3. This is a trivial change. If you [uncomment this line](https://github.com/vbe0201/blog/blob/main/src/post.rs#L89) you can have raw HTML inside the markdown files.
4. No problem, I will do this myself.

**Comment by 7h3730B** [comment]
Thanks for your feedback, I appreciate it!

**Comment by 7h3730B** [comment]
Hey, me again. Just wanted to bring to your attention that anchor heads are working but as you mentioned before, the html needed must be directly put into the markdown file as done [here](https://github.com/vbe0201/blog/blob/f612e029caf66318237e6fd4e37b0fc5baf2becf/posts/how-not-to-provide-secure-access-to-a-secret.md#L21)

**Comment by 7h3730B** [comment]
As it turns out [comrak](https://github.com/kivikakk/comrak) is shipping with syntax highlighting with the help of [syntect](https://github.com/trishume/syntect)

**Comment by 7h3730B** [comment]
I think that should be everything.

I hope you are statisfied with my work. And if you really are I would appreciate if you add the `hacktoberfest-accepted` label

**Comment by vbe0201** [comment]
Thanks again for doing this, heavily appreciated.

**Pull request merged**
